version: "3.9"
services:
  datamicroservice:
    image: ${DOCKER_REGISTRY-}datamicroservice
    build:
      context: "IoTS2021/IoTS Microservice Project/DataMicroservice"
      dockerfile: DataMicroservice/Dockerfile
    ports:
      - "49164:80"
    hostname: "datamicroservice"
  temp-sensor1:
    build: "Python docker/python-sensor-temp/python-sensor-temp-1"
    ports:
      - "5021:5000"
    hostname: "temp-sensor1"
  temp-sensor2:
    build: "Python docker/python-sensor-temp/python-sensor-temp-2"
    ports:
      - "5022:5000"
    hostname: "temp-sensor2"
  temp-sensor3:
    build: "Python docker/python-sensor-temp/python-sensor-temp-3"
    ports:
      - "5023:5000"
    hostname: "temp-sensor3"
  temp-sensor4:
    build: "Python docker/python-sensor-temp/python-sensor-temp-4"
    ports:
      - "5024:5000"
    hostname: "temp-sensor4"
  temp-sensor5:
    build: "Python docker/python-sensor-temp/python-sensor-temp-5"
    ports:
      - "5025:5000"
    hostname: "temp-sensor5"
  cassandra-data:
    image: cassandra
    hostname: "cassandra-data"
    ports:
      - "9042:9042"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
  cassandra-analytics:
    image: cassandra
    hostname: "cassandra-analytics"
  analyticsmicroservice:
    image: ${DOCKER_REGISTRY-}analyticsmicroservice
    build:
      context: "IoTS2021/IoTS Microservice Project/AnalyticsMicroservice"
      dockerfile: AnalyticsMicroservice/Dockerfile
  cassandra-command:
    image: cassandra
    hostname: "cassandra-command"
    ports:
      - "9045:9042"
  commandmicroservice:
    image: ${DOCKER_REGISTRY-}commandmicroservice
    build:
      context: "IoTS2021/IoTS Microservice Project/CommandMicroservice"
      dockerfile: CommandMicroservice/Dockerfile
    ports:
      - "49155:80"
    hostname: "commandmicroservice"
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: "IoTS2021/IoTS Microservice Project/APIGateway"
      dockerfile: APIGateway/Dockerfile
    ports:
      - "49156:80"
    hostname: "apigateway"